### ISSUE TITLE
NoMethodError in Frontend#home

### ISSUE THREAD

**Issue by ghost** [BDMADE/college#87]

**Comment by hmtanbir** [comment]
Could you please describe the error ?

**Comment by suthargk** [comment]
undefined method `name' for nil:NilClass


<section class="promo box box-dark">
  <div class="col-md-9"> 
    <h1 class="section-heading">Why <%= @website.name %></h1>   
  <%= @website.details.html_safe %> 
  </div>   <br><br>
--

**Comment by suthargk** [comment]
undefined method `name' for nil:NilClass

<section class="promo box box-dark">
  <div class="col-md-9">
    <h1 class="section-heading">Why <%= @website.name %></h1>
    <%= @website.details.html_safe %>
  </div>
  <br><br>

error in website.name

**Comment by suthargk** [comment]
undefined method `name' for nil:NilClass




Error in website.name

**Comment by suthargk** [comment]
undefined method `name' for nil:NilClass

<section class="promo box box-dark">
  <div class="col-md-9">
    <h1 class="section-heading">Why <%= @website.name %></h1>
    <%= @website.details.html_safe %>
  </div>
  <br><br>

error in website.name 
/college-master/app/views/frontend/home.html.erb where line #22 raised:
